[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "entities"
version = "0.3.0"
description = "SDK for managing AI entities"
readme = "README.md"
authors = [
  { name = "Francis N.", email = "francis.neequaye@projectdavid.co.uk" }
]
license = { text = "MIT" }  # ✅ This triggers a deprecation warning

requires-python = ">=3.8"

dependencies = [
  "httpx>=0.27.0",
  "pydantic>=2.0.0",
  "python-dotenv",
  "validators",
  "pdfplumber",
  "sentence-transformers"
]

[project.optional-dependencies]
dev = ["pytest"]

[project.urls]
Homepage = "https://github.com/frankie336/entitites_sdk"
Repository = "https://github.com/frankie336/entitites_sdk"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
include = ["entities*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
