# .github/workflows/publish-testpypi.yml

name: Publish TestPyPI

on:
  push:
    tags:
      - 'test-v*'

jobs:
  publish-test:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools
        run: pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish to TestPyPI (dry-run)
        run: |
          twine upload --repository-url https://test.pypi.org/legacy/ \
            --skip-existing \
            -u __token__ -p ${{ secrets.TEST_PYPI_API_TOKEN }} \
            dist/*
