name: Lint, Test, Tag, and Publish

on:
  push:
    branches: ['**']        # run on every branch

permissions:
  contents: write
  id-token: write

env:
  TEST_PYPI_URL:  https://test.pypi.org/simple/
  PROD_PYPI_URL:  https://upload.pypi.org/legacy/
  BASE_URL:       http://localhost:9000/

jobs:
# ─────────────────────────── LINT ───────────────────────────
  lint:
    name: 🧹 Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-lint-${{ hashFiles('**/pyproject.toml') }}
      - run: |
          python -m pip install -U pip setuptools wheel
          pip install -e ".[dev]" --index-url https://pypi.org/simple/
      - run: black --check .
      - run: isort --check .

# ─────────────────────────── TEST ───────────────────────────
  test:
    name: ✅ Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10', '3.11', '3.12' ]
    env:                     # offline flags for HF/Transformers
      TRANSFORMERS_OFFLINE: '1'
      HF_HUB_OFFLINE:        '1'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: ${{ matrix.python-version }} }
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}
      - run: |
          python -m pip install -U pip setuptools wheel
          pip install -e ".[dev]" --index-url https://pypi.org/simple/
      - run: pytest tests/

# ───────────────────────── RELEASE ──────────────────────────
  release:
    name: 🚀 Tag, Build, and Publish
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.ref_type == 'branch' && (github.ref_name == 'main' || github.ref_name == 'master' || github.ref_name == 'dev') }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          python -m pip install -U pip setuptools wheel build
          pip install -e ".[dev]" --index-url https://pypi.org/simple/
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: |
          npm install -g semantic-release \
            @semantic-release/git \
            @semantic-release/changelog \
            @semantic-release/github \
            @semantic-release/exec \
            conventional-changelog-conventionalcommits
      - run: npx semantic-release
        env: { GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
      - run: python -m build
      - run: |
          ls -lh dist
          test "$(ls -A dist)" || (echo "dist is empty" && exit 1)
      - id: repo
        run: |
          if [[ "${{ github.ref_name }}" =~ ^(main|master)$ ]]; then
            echo "repo_url=${{ env.PROD_PYPI_URL }}"        >> "$GITHUB_OUTPUT"
            echo "pypi_token_name=PROD_PYPI_TOKEN"          >> "$GITHUB_OUTPUT"
          elif [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "repo_url=${{ env.TEST_PYPI_URL }}"        >> "$GITHUB_OUTPUT"
            echo "pypi_token_name=TEST_PYPI_TOKEN"          >> "$GITHUB_OUTPUT"
          else
            echo "::error::unknown publish target"; exit 1
          fi
      - uses: pypa/gh-action-pypi-publish@release/v1
        if: steps.repo.outputs.pypi_token_name != ''
        with:
          user: '__token__'
          password: ${{ secrets[steps.repo.outputs.pypi_token_name] }}
          repository_url: ${{ steps.repo.outputs.repo_url }}
          skip-existing: true
